devops:
  description: FPTU DSC DevOps branches
  admin: false
  member_username:
    - kaitoz11
    - YP2743
    - TranNgocNam2
frontend:
  description: Group consist of member in DevOps branches
  admin: false
  member_username: 
   - dangtrannam

backend:
  description: Group consist of member in DevOps branches
  admin: false
  member_username: 
   - dangtrannam

branch_leader:
  description: Group consist of all leader in all branches
  admin: false
  member_username:
    - quangdatpham
    - pphuc25
    - trungkien100823

operator:
  description: Group consist of github organization owner
  admin: true 
  member_username:
    - quangdatpham
    - baolongv3